### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by 3ffusi0on** [codepath/android-oauth-handler#12]
The link for the avaible services is not existing anymore. line 59 of Readme.md

(https://github.com/fernandezpablo85/scribe-java/tree/master/src/main/java/org/scribe/builder/api)

**Comment by nesquena** [comment]
Fixed to https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/main/java/com/github/scribejava/apis thanks!
