### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ApoorvKhatreja** [codepath/android-oauth-handler#15]
This library being on Github makes it open source, but I was wondering what your stand is on commercial use of this code?

**Comment by nesquena** [comment]
This code was built and is tested primarily in the context of our classes. It works really well for simple projects and portfolio pieces. I'm not sure I would stand behind this library for commercial or production use though. That said, you are more than welcome to try. Use at your own risk :)

**Comment by ApoorvKhatreja** [comment]
Thanks! Risk is always implicit with open source projects.

My question was more in the context of intellectual property. Since you've chosen not to add a license, as per Github's licensing policy, default copyright laws apply: you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work.

https://help.github.com/articles/open-source-licensing/

I'm just trying to cover any legal bases before using this in a project. Would you consider adding a license such as MIT or Apache?

**Comment by ApoorvKhatreja** [comment]
Thanks for merging the PR!
