### ISSUE TITLE
How to get user info on initial login?

### ISSUE THREAD

**Issue by rhyshalsey** [codepath/android-oauth-handler#25]
Is it possible to get all the response data when authentication is complete? I am currently using the library to log in to Flickr, which works. However, [Flickr's api sends user info (id & username)](https://www.flickr.com/services/api/auth.oauth.html) along with the token and secret when login is successful. I have no problem accessing the token and secret, but I can't seem to access the user info or any other info sent with the response. If I try to access the raw response, where I could get the user's info, I get the following message : 
> This token object was not constructed by scribe and does not have a rawResponse

How can I access the rest of the response data?

Thank you

**Comment by rogerhu** [comment]
You can't but you should be able to use https://www.flickr.com/services/api/flickr.test.login.html?
