### ISSUE TITLE
Gradle Sync fails - 

### ISSUE THREAD

**Issue by talbenyam** [codepath/android-oauth-handler#36]
I tried to add 'compile 'com.codepath.libraries:android-oauth-handler:1.1.2' to: android-rest-client-template, but it fails...

Error:(41, 13) Failed to resolve: com.codepath.libraries:android-oauth-handler:1.1.2
master/app/build.gradle"

Error:Failed to resolve: annotationProcessor
master/app/build.gradle"

**Comment by nesquena** [comment]
Yes, we are in the process of releasing some significant updates to this library, to use it, you'll want to go back to https://github.com/codepath/android-oauth-handler/tree/ff9c01c8d45f3f8508503487361e3da69fe24a21

**Comment by talbenyam** [comment]
Thanks for your fast reply, the problem is that 1.1.0 version does not work
for my OAuth 2.0 needs.

When do expect it to be ready?

Best regards,
Tal Benyamin

**Comment by rogerhu** [comment]
OAuth2 works now.  It does not have support for refresh tokens (PR welcome)

https://github.com/codepath/android-rest-client-template#adding-oauth2-support
